attach(Readmissions)
head(Readmissions)
tapply(hospital_name, list(region_name, measure_name), length)
ReadmRate<-number_of_readmissions/number_of_discharges
tapply(ReadmRate, list(region_name, measure_name), mean)
hist(ReadmRate[measure_name=="READM-30-AMI-HRRP"], main="Histogram of AMI Readmissions", xlab="Readmission Rate")
hist(ReadmRate[measure_name=="READM-30-HF-HRRP"], main="Histogram of HF Readmissions", xlab="Readmission Rate")
hist(ReadmRate[measure_name=="READM-30-PN-HRRP"], main="Histogram of PN Readmissions", xlab="Readmission Rate")
anova1<-aov(ReadmRate[measure_name=="READM-30-AMI-HRRP"]~region_name[measure_name=="READM-30-AMI-HRRP"])
summary(anova1)
TukeyHSD(anova1, ordered=T)
anova2<-aov(ReadmRate[measure_name=="READM-30-HF-HRRP"]~region_name[measure_name=="READM-30-HF-HRRP"])
summary(anova2)
TukeyHSD(anova2, ordered=T)
anova3<-aov(ReadmRate[measure_name=="READM-30-PN-HRRP"]~region_name[measure_name=="READM-30-PN-HRRP"])
summary(anova3)
TukeyHSD(anova3, ordered=T)
