attach(HAP)
summary(avg_value)
summary(lbw)
summary(vlbw)
summary(premature)
hist(lbw, xlab="Average Births Considered Low Birth Weight by US county")
hist(vlbw, xlab="Average Births Considered Very Low Birth Weight by US county")
hist(premature, xlab="Average Births Considered premature by US county")
hist(avg_value, xlab="Average Lead PM2.5 LC by US County")
lin1<- lm(lbw~avg_value)
summary(lin1)
plot(lbw~avg_value)
abline(lin1, col="red")
lin2<- lm(vlbw~ avg_value)
summary(lin2)
plot(vlbw~avg_value)
abline(lin2, col="red")
lin3<- lm(premature~ avg_value)
summary(lin3)
plot(premature~ avg_value)
abline(lin3, col="red")
