attach(nurse_staff)
table(owner_group)
table(hosp)
tapply(total,owner_group,mean) 
tapply(rn,owner_group,mean) 
tapply(total,hosp,mean)
tapply(rn,hosp,mean)
tapply(ulcer,owner_group,mean)
tapply(ulcer,hosp,mean)
t.test(ulcer~hosp,paired=F)
t.test(total~hosp,paired=F)
t.test(rn~hosp,paired=F)
anova1a<-aov(ulcer~owner_group*hosp)
summary(anova1a)
TukeyHSD(anova1a, ordered=T)
anova2a<-aov(total~owner_group*hosp)
summary(anova2a)
TukeyHSD(anova2a, ordered=T)
anova3a<-aov(rn~owner_group*hosp)
summary(anova3a)
TukeyHSD(anova3a, ordered=T)
lin1<-lm(ulcer[owner_group=="For profit"]~rn[owner_group=="For profit"])
summary(lin1)
plot(ulcer[owner_group=="For profit"]~rn[owner_group=="For profit"], col="red", xlab="adj_rn", ylab="avg_value")
abline(lin1, col="darkred")
lin2<-lm(ulcer[owner_group=="Non profit"]~rn[owner_group=="Non profit"])
summary(lin2)
points(ulcer[owner_group=="Non profit"]~rn[owner_group=="Non profit"], col="pink") 
abline(lin2, col="darkgray")
lin3<-lm(ulcer[owner_group=="Government"]~rn[owner_group=="Government"])
summary(lin3)
points(ulcer[owner_group=="Government"]~rn[owner_group=="Government"], col="darkred") 
abline(lin3, col="black")
legend("topright", c("Government","Non Profit", "For Profit"),col=c("black","darkgray","darkred"), pch=c(1,1,1))
