attach(hcahps_and_efficiency)
summary(hcahps_and_efficiency)
summary(percent[Q_Revised=="No"])
summary(percent[Q_Revised=="Yes_probably"])
summary(percent[Q_Revised=="Yes_definitely"])
hist(score) 
hist(percent[Q_Revised=="No"], main="Reported NO, they would probably\n not or definitely not recommend the hospital", xlab="Percent")
hist(percent[Q_Revised=="Yes_probably"], main="Reported YES, they would probably\n recommend the hospital", xlab="Percent")
hist(percent[Q_Revised=="Yes_definitely"], main="Reported YES, they would definitely\n recommend the hospital", xlab="Percent")
lin1<-lm(score[Q_Revised=="No"]~ percent[Q_Revised=="No"])
summary(lin1)
plot(score[Q_Revised=="No"]~ percent[Q_Revised=="No"], xlab="Percent said No", ylab="Time")
abline(lin1, col="red")
lin2<-lm(score[Q_Revised=="Yes_probably"]~ percent[Q_Revised=="Yes_probably"])
summary(lin2)
plot(score[Q_Revised=="Yes_probably"]~ percent[Q_Revised=="Yes_probably"], xlab="Percent said Probably", ylab="Time")
abline(lin2, col="red")
lin3<-lm(score[Q_Revised=="Yes_definitely"]~ percent[Q_Revised=="Yes_definitely"])
summary(lin3)
plot(score[Q_Revised=="Yes_definitely"]~percent[Q_Revised=="Yes_definitely"], xlab="Percent said Yes", ylab="Time")
abline(lin3, col="red")
