attach(pt_sat)
summary(mspb)
hist(mspb)
hist(uw.pt.ex.sc)
tapply(mspb,pt.ex.group,mean)
tapply(mspb,pt.ex.group,sd)
boxplot(mspb~pt.ex.group, ylab="MSPB Rate", xlab="Patient Experience of Care Domain Score Groups")
anova1<-aov(mspb~as.factor(pt.ex.group))
summary(anova1)
TukeyHSD(anova1)
lin1<- lm(mspb~uw.pt.ex.sc)
summary(lin1)
plot(mspb~uw.pt.ex.sc, xlab="Patient Experience of Care Domain Score", ylab="MSPB Rate")
abline(lin1, col="red")
