attach(PreventCare)
summary(PreventCare)
PreventCare<-subset(PreventCare, !is.na(mammogram))
detach(PreventCare)
attach(PreventCare)
summary(PreventCare)
View(PreventCare)
summary(mammogram)
par(mfrow=c(2,2))
plot(mammogram, uninsured,xlab="Mammography",ylab="Proportion Uninsured", main="Mammogram vs. Uninsured")
plot(mammogram,poverty,xlab="Mammography",ylab="Rate of Poverty", main="Mammogram vs. Poverty")
boxplot(mammogram, chc, xlab="Community Health Center",ylab="Mammography",main="Mammogram Rates in Presence of CHC", names=c("Yes","No"))
plot(mammogram,phys_rate,xlab="Mammography",ylab="Rate of Primary Care Physicians", main="Mammogram vs. Primary Care")
US_Mammogram_lm <- lm(mammogram ~ poverty + uninsured + as.factor(chc) + phys_rate) 
list(mammogram)
summary(US_Mammogram_lm)
US_Mammogram_interact_lm <- lm(mammogram ~ poverty * uninsured * as.factor(chc)* phys_rate) 
summary(US_Mammogram_interact_lm)